name: Production Deploy

on:
    push:
        branches:
            - master

jobs:
    Check_App:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2

            - name: Inject slug/short variables
              uses: rlespinasse/github-slug-action@v3.x

            - name: Install NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Cache node_modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}

            - name: Install Packages
              run: yarn install --frozen-lockfile

            - name: Generate Environment Variables
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_REACT_APP_ENV: production
                  envkey_REACT_APP_KAKAO_KEY: ${{ secrets.REACT_APP_KAKAO_KEY }}
                  file_name: .env

            - name: Build
              run: yarn build

            - name: Deploy - PROD
              env:
                  CI: false
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  yarn deploy

            - name: Slack Notification on Success
              if: success()
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                  text: '*<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|MySpot-Web Deploy Succeed::${{ env.GITHUB_REF_SLUG }}>*'
                  attachments: |
                      [
                        {
                          "title": "Deploy succeed",
                          "color": "good",
                          "author_name": "${{ github.actor }}",
                          "author_icon": "${{ github.event.sender.avatar_url }}"
                        }
                      ]

            - name: Slack Notification on Failure
              if: failure()
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                  text: '*<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|MySpot-Web Deploy Failure::${{ env.GITHUB_REF_SLUG }}>*'
                  attachments: |
                      [
                        {
                          "title": "Deploy failure",
                          "color": "danger",
                          "author_name": "${{ github.actor }}",
                          "author_icon": "${{ github.event.sender.avatar_url }}"
                        }
                      ]
