name: Pull Request

on:
    pull_request:
        types: [opened, reopened]

jobs:
    Check_App:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2

            - name: Inject slug/short variables
              uses: rlespinasse/github-slug-action@v3.x

            - name: Install NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Check Lint & Stylelint
              run: yarn lint & yarn stylelint

            - name: Build
              run: yarn build

            - name: Slack Notification on Success
              if: success()
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                  text: '*<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|WEB Pull Request Succeed::${{ env.GITHUB_REF_SLUG }}>*'
                  attachments: |
                      [
                        {
                          "title": "사전 검증에 성공하였습니다.",
                          "color": "good",
                          "author_name": "${{ github.actor }}",
                          "author_icon": "${{ github.event.sender.avatar_url }}"
                        }
                      ]

            - name: Slack Notification on Failure
              if: failure()
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                  text: '*<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|WEB Pull Request Failure::${{ env.GITHUB_REF_SLUG }}>*'
                  attachments: |
                      [
                        {
                          "title": "사전 검증에 실패하였습니다.",
                          "color": "danger",
                          "author_name": "${{ github.actor }}",
                          "author_icon": "${{ github.event.sender.avatar_url }}"
                        }
                      ]
